### ISSUE TITLE
suggestions for api

### ISSUE THREAD

**Issue by chassain** [TheBodger/MMM-Consumer-Flights#2]
Hello,

Hope you're fine..after many days the module is working fine. i have changed names in french to understand better. I can see planes last one day or after day and not only the day of today but it doesn't matter..
I have only one suggestion to work better but i'm not sure if possible. With an api i have to manipulate the datarefresh because my mirror is working between 6 and 14 hours...i can pay of course but it is possible to add other api keys and have a scrool when first api is over, turn on api 2, etc....and my datafresh will be less (3 hours to 1 hour)..sorry for english. Hope you understand the idea in adding many api keys in config and regulate these

have a good time

**Comment by TheBodger** [comment]
Hello, 

I do understand and i think i have an idea how to do it easily. 

i will add a delay to the config in millieseconds that means each provider will wait that time before it starts calling the API. 

This will allow as many provider modules as you need, each with different API key and each with different delay.

4 api keys, data refresh 4 hours:

provider1; API key1,datarefresh 4 hours, delay 0 hours
provider2; API key2,datarefresh 4 hours, delay 1 hours
provider3; API key3,datarefresh 4 hours, delay 2 hours
provider4; API key4,datarefresh 4 hours, delay 3 hours

in the excel, you can see when each api call is made

![image](https://user-images.githubusercontent.com/41484656/88487587-7c82d780-cf7e-11ea-8520-4ba1c2a40b35.png)

i will make the change and test and share when it is ready - maybe a few days!

Thanks for the idea, it is very good !!

did you change the names in the theme folder? (in theme.js) This was designed to allow you to have different names (or add names in french)

**Comment by chassain** [comment]
just change compagny, from, to...in french...
you are just a king..it seems so easy for you....

So thanks

**Comment by chassain** [comment]
But it s not really like this..for only one provider (arrivals toulon for example) i have to enter X api keys to turn with 1 hours datarefresh..but we can imagine all provider have the same data (arrivales toulon)..so, it could be ok

**Comment by TheBodger** [comment]
yes that is correct - i will show you the config soon.

**Comment by TheBodger** [comment]
i have made the change and updated github. the readme has an example config that you can use / change to use the different APIs. Any problems let me know

cd /modules/MM-Provider-JSON
git pull

**Comment by chassain** [comment]
It's simply a great...great...great..job...thanks for this work
refresh all 90 minutes with the same delay with 2 api...

**Comment by TheBodger** [comment]
thanks. it is always fun !
